import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "./style.scss"
// import Layout from "./components/HOC/Layout/Layout";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const DynamicLayout = dynamic(() => import('./components/HOC/Layout/Layout'), { ssr: false });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="main-body">
        <section className="pageContent">
          <div className="leftContent">
            <DynamicLayout>
              {children}
            </DynamicLayout>
          </div>
          <div className="rightContent">
            <div className="contentBody">
              
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
