import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "./style.scss"
import Providers from "@/redux/Provider";
import Loader from "./components/Utils/Modals/Loader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description:
   "Generated by create next app",
};
export const viewport: Viewport = {
  // width: 500,
  maximumScale: 1,
  minimumScale: 1,
  initialScale: 1,
  userScalable: false,
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className} id="main-body">
        <section className="pageContent">
          <div className="leftContent">
            <Providers>
              <Loader />
              {children}
            </Providers>
          </div>
          <div className="rightContent">
            <div className="contentBody">
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
